---
title: Compendium Finance (TM)
timezone: UTC
collections:
  assets:
    title: Assets
    output: true
  modals:
    title: Modals
    output: false
  posts:
    title: Posts
    output: true
  promos:
    title: Promos
    output: false
  tools:
    title: Tools
    output: false
  top-sections:
    title: Top Sections
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: tools
  values:
    layout: blogtool
email: your-email@compendiumfinance.com
description: 'This is the static content site for compendiumfinance.com

'
baseurl: 
url: http://compendiumfinance.com
twitter_username: choosesimple
github_username: jekyll
trademark: Compendium Finance&#x2122;
social: compendiumfinance
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
assets:
  compress:
    css: true
    js: true
