# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Compendium Finance (TM)
email: your-email@compendiumfinance.com
description: > # this means to ignore newlines until "baseurl:"
  This is the static content site for compendiumfinance.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://compendiumfinance.com" # the base hostname & protocol for your site
twitter_username: choosesimple
github_username:  jekyll

trademark: Compendium Finance&#x2122;
social: compendiumfinance

# Build settings
markdown: kramdown

collections:
  posts:
  tools:
  promos:
  top-sections:
  modals:
  assets:
    output: true

defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: tools
  values:
    layout: blogtool

sass:
  sass_dir: _sass
  style: compressed
assets:
  compress:
    css: true
    js: true

